REM *** LESSON 56: INSTRUCTIONS SCREEN ***
REM Practical Example
10 REM *** PAGED INSTRUCTIONS ***
20 PRINT CHR$(147)
30 P=1
40 PRINT CHR$(19)
50 PRINT "*** INSTRUCTIONS ***"
60 PRINT
70 IF P=1 THEN PRINT "CONTROLS:":PRINT:PRINT "W = UP":PRINT "S = DOWN":PRINT "A = LEFT":PRINT "D = RIGHT":PRINT "SPACE = FIRE"
80 IF P=2 THEN PRINT "RULES:":PRINT:PRINT "AVOID RED ENEMIES":PRINT "COLLECT GREEN ITEMS":PRINT "REACH EXIT TO WIN"
90 IF P=3 THEN PRINT "SCORING:":PRINT:PRINT "ENEMY: 10 POINTS":PRINT "ITEM: 50 POINTS":PRINT "WIN: 500 BONUS"
100 PRINT
110 PRINT "PAGE";P;"/3"
120 PRINT
130 PRINT "N=NEXT P=PREV SPACE=START"
140 GET K$
150 IF K$="N" AND P<3 THEN P=P+1:GOTO 40
160 IF K$="P" AND P>1 THEN P=P-1:GOTO 40
170 IF K$=" " THEN PRINT CHR$(147):PRINT "STARTING...":END
180 GOTO 40