REM *** LESSON 49: TITLE SCREEN WITH ANIMATION ***
REM Basic Example
10 REM *** SIMPLE TITLE ***
20 PRINT CHR$(147)
30 PRINT
40 PRINT "  *** SPACE RAIDERS ***"
50 PRINT
60 PRINT "    PRESS FIRE TO START"
70 PRINT
80 GET K$:IF K$="" THEN GOTO 80
90 PRINT "GAME STARTS HERE..."