REM Movement skeleton
GET K$: IF K$="" THEN RETURN
NX=PX: NY=PY
IF K$="A" THEN NX=PX-1
IF MAP(NY,NX)=1 THEN RETURN
IF NX<1 OR NX>MAX THEN RETURN
POKE SCREEN+PY*40+PX,32
PX=NX: PY=NY
POKE SCREEN+PY*40+PX,PLAYER_CHAR
