REM Scroll timing
ti$="000000"
STEP=5:NEXTT=STEP
IF TI>=NEXTT THEN NEXTT=NEXTT+STEP

REM World coordinates
WORLDX=OFFSET+PX
ENPOS=ENX-OFFSET+1

REM Victory buffer
IF OFFSET<LAST THEN WINCOUNT=0 ELSE WINCOUNT=WINCOUNT+1
IF WINCOUNT>30 THEN WIN!
