REM Spawn countdown
IF PU_STATE=0 THEN SPAWN=SPAWN-1
IF SPAWN=0 THEN GOSUB 4200

REM Buff timer
IF PU_STATE=2 THEN BUFF=BUFF-1:IF BUFF=0 THEN GOSUB 4600

REM Collision test
COL=PEEK(53279)
IF PU_STATE=1 AND (COL AND PLAYER) AND (COL AND POWER) THEN GOSUB 4400
