#!/usr/bin/env python3
"""
convert_sprite.py — Shadowkeep sprite shifter

Reads a PNG sprite (typically 16×16) and emits a Z80 assembly .inc file
containing pre-shifted versions of the sprite for all 8 X-offsets,
with interleaved (image, mask) byte pairs ready for the masked-draw primitive.

Spec: wiki/curriculum/shadowkeep-32-sprite-shifter.md

PNG conventions:
    - Alpha-based (default): pixels with alpha=0 are transparent (mask preserves
      background). Opaque pixels with the designated "ink" colour (default:
      pure black #000000) set the image bit; other opaque colours leave the
      image bit clear (sprite pixel is visible as cell-attribute paper).
    - Magenta-key (--magenta): bright magenta (#FF00FF) marks transparent;
      ink colour as above.

Output format:
    Each shift produces 16 rows × 3 bytes (image, mask interleaved) = 96 bytes.
    Total per source frame: 8 × 96 = 768 bytes.

Example:
    python convert_sprite.py \\
        --input  assets/game-01-shadowkeep/sprites/hero/walk-down-0.png \\
        --output game-01-shadowkeep/sprites/hero_walk_down_0.inc \\
        --label  hero_walk_down_0 \\
        --shifts 8

Requires Pillow (PIL) for PNG decoding:
    pip install Pillow
"""

import argparse
import sys
from pathlib import Path


def load_png(path, transparency_mode, ink_color):
    """Load PNG and return a 2D array of bits (image_bit, mask_bit) per pixel.

    image_bit: 1 if pixel is sprite content (set/ink), 0 otherwise
    mask_bit: 1 if pixel is transparent (preserve background), 0 if opaque
    """
    try:
        from PIL import Image
    except ImportError:
        sys.exit("error: Pillow required. Install with: pip install Pillow")

    img = Image.open(path)
    img = img.convert("RGBA")
    width, height = img.size
    pixels = img.load()

    grid = []
    for y in range(height):
        row = []
        for x in range(width):
            r, g, b, a = pixels[x, y]
            if transparency_mode == "alpha":
                transparent = (a == 0)
            elif transparency_mode == "magenta":
                transparent = (r == 255 and g == 0 and b == 255)
            else:
                raise ValueError(f"unknown transparency mode: {transparency_mode}")

            if transparent:
                image_bit = 0
                mask_bit = 1
            else:
                # Opaque: check if ink colour
                ir, ig, ib = ink_color
                is_ink = (r == ir and g == ig and b == ib)
                image_bit = 1 if is_ink else 0
                mask_bit = 0
            row.append((image_bit, mask_bit))
        grid.append(row)

    return grid, width, height


def generate_shifts(grid, width, height, num_shifts, output_width_bytes):
    """For each shift 0..num_shifts-1, produce (image_bytes, mask_bytes)
    rows of length output_width_bytes.

    Returns a list of shifts; each shift is a list of (image_byte, mask_byte) tuples
    representing the bytes of each row.
    """
    shifts = []
    output_width_bits = output_width_bytes * 8

    for shift in range(num_shifts):
        rows = []
        for y in range(height):
            for out_byte_idx in range(output_width_bytes):
                image_byte = 0
                mask_byte = 0
                for bit_in_byte in range(8):
                    out_x = out_byte_idx * 8 + bit_in_byte
                    src_x = out_x - shift
                    if 0 <= src_x < width:
                        image_bit, mask_bit = grid[y][src_x]
                    else:
                        # Outside source bounds: transparent (mask=1, image=0)
                        image_bit, mask_bit = 0, 1
                    # Bit 7 is leftmost on Spectrum bitmap byte
                    image_byte |= image_bit << (7 - bit_in_byte)
                    mask_byte |= mask_bit << (7 - bit_in_byte)
                rows.append((image_byte, mask_byte))
        shifts.append(rows)

    return shifts


def emit_inc(shifts, label, height, output_width_bytes, source_path, output_path):
    """Write the .inc file with all shifts, interleaved (image, mask) bytes."""
    bytes_per_row = output_width_bytes * 2  # image byte + mask byte per output byte
    bytes_per_shift = height * bytes_per_row
    total_bytes = len(shifts) * bytes_per_shift

    lines = []
    lines.append(f"; Generated by convert_sprite.py")
    lines.append(f"; Source: {source_path}")
    lines.append(f"; Size: {output_width_bytes * 8}×{height} (output, after shift padding)")
    lines.append(f"; {len(shifts)} pre-shifted versions, interleaved (image, mask) pairs")
    lines.append(f"; Each shift: {height} rows × {output_width_bytes} cols × 2 bytes = {bytes_per_shift} bytes")
    lines.append(f"; Total: {len(shifts)} × {bytes_per_shift} = {total_bytes} bytes")
    lines.append(f";")
    lines.append(f"; Layout per row: image_0, mask_0, image_1, mask_1, ...")
    lines.append(f"")

    for shift_idx, rows in enumerate(shifts):
        lines.append(f"{label}_shift_{shift_idx}:")
        for row_idx in range(height):
            row_bytes = []
            for col_idx in range(output_width_bytes):
                offset = row_idx * output_width_bytes + col_idx
                image_byte, mask_byte = rows[offset]
                row_bytes.append(f"${image_byte:02x}")
                row_bytes.append(f"${mask_byte:02x}")
            lines.append(f"    defb " + ", ".join(row_bytes) + f"   ; row {row_idx}")
        lines.append("")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {output_path} ({total_bytes} bytes of sprite data)")


def parse_hex_color(s):
    s = s.lstrip("#")
    if len(s) != 6:
        raise argparse.ArgumentTypeError(f"colour must be 6 hex digits, got: {s}")
    return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))


def main():
    ap = argparse.ArgumentParser(
        description="Convert a PNG sprite to a Z80 .inc with pre-shifted, masked data."
    )
    ap.add_argument("--input", required=True, help="source PNG path")
    ap.add_argument("--output", required=True, help="destination .inc path")
    ap.add_argument("--label", required=True, help="assembly label prefix")
    ap.add_argument(
        "--shifts",
        type=int,
        default=8,
        help="number of pre-shifted versions to generate (default 8; use 1 for cell-aligned-only)",
    )
    transparency = ap.add_mutually_exclusive_group()
    transparency.add_argument(
        "--alpha",
        action="store_const",
        dest="mode",
        const="alpha",
        help="use alpha channel for transparency (default)",
    )
    transparency.add_argument(
        "--magenta",
        action="store_const",
        dest="mode",
        const="magenta",
        help="use bright magenta (#FF00FF) for transparency",
    )
    ap.add_argument(
        "--ink",
        type=parse_hex_color,
        default="#000000",
        help="ink colour as #RRGGBB (default: #000000 black)",
    )
    args = ap.parse_args()

    mode = args.mode or "alpha"

    grid, width, height = load_png(args.input, mode, args.ink)

    # Output width in bytes: for 16-wide source with shift > 0, needs 3 bytes
    # to accommodate the shifted right edge. Pad to 3 bytes uniformly even
    # for shift 0 to keep the runtime draw loop uniform.
    if args.shifts == 1:
        # Cell-aligned only: just enough bytes to cover the source width
        output_width_bytes = (width + 7) // 8
    else:
        # Pre-shifted: source width + max shift, rounded up
        max_extra_bits = args.shifts - 1
        output_width_bytes = (width + max_extra_bits + 7) // 8

    shifts = generate_shifts(grid, width, height, args.shifts, output_width_bytes)

    emit_inc(
        shifts,
        label=args.label,
        height=height,
        output_width_bytes=output_width_bytes,
        source_path=args.input,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
