10 INPUT "COMMAND";CM$
20 CM$=CM$+" "
30 SPACEPOS=LEN(CM$)
40 FOR I=1 TO LEN(CM$)
50 IF MID$(CM$,I,1)=" " THEN SPACEPOS=I:I=LEN(CM$)
60 NEXT I
70 VB$=LEFT$(CM$,SPACEPOS-1)
80 OB$=MID$(CM$,SPACEPOS+1,LEN(CM$)-SPACEPOS)
90 PRINT "VERB:";VB$
100 PRINT "OBJECT:";OB$
