REM Insert score
FOR I=1 TO 5
  IF NS>SC(I) THEN POS=I:GOTO 230
NEXT I
RETURN

230 FOR J=5 TO POS+1 STEP -1
  SC(J)=SC(J-1)
NEXT J
SC(POS)=NS
NAME$(POS)=N$

REM Disk save
OPEN 1,8,2,"HISCORE,S,W"
FOR I=1 TO 5:PRINT#1,NAME$(I);",";SC(I):NEXT I:CLOSE 1
