export const lessons=[
{
 title:'Place a point',
 intro:'A position answers two questions: how far across, and how far up? Move the point using its coordinates before we ask it to travel.',
 help:'Change X and Y, or drag the point. The controls provide the same experiment with a keyboard.',
 prose:`<h2>Choose an origin</h2><p>The crossing of the axes is our origin: (0, 0). Coordinates are written (x, y), with the horizontal value first. A point at (120, 90) lies 120 units right of the origin and 90 units above it. These are world units; resizing the picture does not change the point’s position.</p><p>Make X negative while leaving Y at 90. The point crosses to the left, but stays at the same height. Now make Y negative too. The signs tell us which side of each axis contains the point.</p><h2>Position and movement</h2><p>A position is where something is. A displacement is the change from one position to another. To get from (20, 30) to (120, 90), subtract start from finish: Δx = 120 − 20 = 100 and Δy = 90 − 30 = 60. The symbol Δ means “change in”.</p><details class="question"><summary>From (120, 90), move 30 units left and 50 units down. Where will the point end up?</summary><p>(90, 40): add −30 to X and −50 to Y. A negative change does not necessarily produce a negative position.</p></details><p>Set that result using the controls. If a point moves in the wrong direction, check the coordinate order and the signs. Many screen APIs count Y downwards; this experiment keeps world Y upwards and reverses it only when drawing.</p>`
},
{
 title:'Measure the triangle',
 intro:'A straight route and an across-then-up route reach the same point. Their lengths are different. The right triangle lets us measure the straight route.',
 help:'The horizontal and vertical legs meet at a right angle. The sloping side joins the origin to the point.',
 prose:`<h2>Three sides, one relationship</h2><p>Start at (120, 90). Going across and then up travels 120 + 90 = 210 units. The straight line is shorter. It forms the <strong>hypotenuse</strong>: the side opposite the right angle.</p><p>For a right triangle, Pythagoras gives r² = x² + y². Squaring means multiplying a number by itself. Here 120² + 90² = 14,400 + 8,100 = 22,500. Its positive square root is 150, so the straight distance is 150 units.</p><p>The experiment calculates that distance as you change the point. Change X to −120. The coordinate is negative, but the side length is 120. Squaring removes the sign: (−120) × (−120) = 14,400. Distance stays non-negative.</p><details class="question"><summary>Double both coordinates to (240, 180). Does the distance double or quadruple?</summary><p>It doubles to 300. Each squared term quadruples, giving 90,000, but the square root brings the factor back to two. The triangle keeps its shape.</p></details><h2>Separate direction from size</h2><p>At (120, 90), the horizontal share of the sloping side is 120 / 150 = 0.8 and the vertical share is 90 / 150 = 0.6. At (240, 180), those ratios are still 0.8 and 0.6. They describe the same direction at a different distance.</p><p>Try (0, 0). Distance is zero and there is no direction to describe; dividing by zero cannot produce these shares. The experiment marks them as undefined.</p>`
},
{
 title:'Turn an angle into movement',
 intro:'Instead of choosing X and Y separately, choose a direction and a distance. Sine and cosine supply the two coordinates.',
 help:'The circle has the chosen radius. The triangle shows the horizontal and vertical parts of that radius.',
 prose:`<h2>Name the two shares</h2><p>Measure the angle anticlockwise from the positive X axis. In the first quadrant, cosine is the adjacent side divided by the hypotenuse: x / r. Sine is the opposite side divided by the hypotenuse: y / r. Rearranging gives <strong>x = r × cos(angle)</strong> and <strong>y = r × sin(angle)</strong>.</p><p>At 30°, cosine is about 0.866 and sine is 0.5. With radius 150, X is about 129.904 and Y is 75. Set the angle to 30° and the radius to 150, then check the picture. The results are coordinates, not two different distances from the origin.</p><p>Change the radius to 225 while keeping the angle. The point moves along the same line: the shares stay constant. Change the angle to 150°. X becomes negative and Y stays positive. Around the whole circle, sine and cosine are signed components, even though triangle side lengths are never negative.</p><h2>Use speed instead of radius</h2><p>To move 3 units per tick along that direction, use vx = 3 × cos(angle) and vy = 3 × sin(angle). Add vx to position X and vy to position Y each tick. The experiment shows these velocity components separately from the enlarged triangle.</p><details class="question"><summary>At 90°, what are the two velocity components for speed 3?</summary><p>vx = 0 and vy = 3. All movement is upwards. At 180°, they are −3 and 0, giving movement to the left. Tiny floating-point residues near zero are rounded in the display.</p></details><p>At 45°, both components are about 2.121. Giving each component the full speed 3 would produce a diagonal speed of √18, about 4.243. Components combine geometrically; they do not each inherit the total speed.</p>`
},
{
 title:'Measure angles in radians',
 intro:'A full turn can be measured as 360 degrees or 2π radians. The direction is unchanged; the number and its unit change.',
 help:'The highlighted arc measures the entered angle. Its length is radius × angle in radians.',
 prose:`<h2>Measure the turn using its circle</h2><p>A radian is the angle made when an arc’s length equals the circle’s radius. The circumference of a circle is 2πr. Divide by r and one full turn is 2π radians, approximately 6.283185.</p><p>That gives the conversion: radians = degrees × π / 180. Going back, degrees = radians × 180 / π. A quarter turn is 90° = π/2 radians; half a turn is 180° = π radians.</p><p>Use the π/2 button. The point lies above the origin. Increase the radius: the arc becomes longer, but the angle is still π/2. Arc length divided by radius stays the same. This is why radians are useful when working with circular motion.</p><details class="question"><summary>A circle has radius 100. You travel an arc of length 100. Have you turned 1 degree or 1 radian?</summary><p>1 radian: angle = arc / radius = 100 / 100. That is about 57.296°, much larger than 1°.</p></details><h2>Know the function’s convention</h2><p>JavaScript’s Math.sin and Math.cos take radians. To calculate the sine of 30°, pass 30 × π / 180, giving about 0.5. Passing the bare number 30 asks for the sine of 30 radians, about −0.988. The function cannot guess which unit you intended.</p><p>This experiment labels its input in radians and reports degrees alongside it. Enter 1 and compare its direction with π/2. A rounded decimal approximation to π/2 can leave a small horizontal component; the preset uses JavaScript’s π value.</p>`
},
{
 title:'Find the angle to a target',
 intro:'We know where the target is. Now work backwards from its coordinates to a direction, then test that direction with a shot.',
 help:'Aim with the angle control or drag on the range. Reveal the calculated direction after making a prediction.',
 prose:`<h2>Subtract before finding the angle</h2><p>For a launcher at (sx, sy) and target at (tx, ty), calculate Δx = tx − sx and Δy = ty − sy. Our launcher is at (0, 0), so these differences equal the target coordinates.</p><p>Tangent relates the two components: tan(angle) = Δy / Δx. Its inverse, atan, can recover an angle from a ratio, but the ratio loses information. Targets at (100, 100) and (−100, −100) both give a ratio of 1, although they lie in opposite directions.</p><p><strong>atan2(Δy, Δx)</strong> accepts the two components separately, retaining their signs. It also handles a vertical direction without dividing by Δx = 0. At the origin itself, no direction is defined. Our targets always have a non-zero distance.</p><details class="question"><summary>For target (−100, 100), should the angle be 45° or 135°?</summary><p>135°. X is negative and Y is positive, so the direction points up and left. atan(100 / −100) gives −45°, which points down and right instead.</p></details><h2>Predict, calculate, fire</h2><p>Try a manual shot first. Reveal the calculation, use its angle and fire again. Next target visits other quadrants and a vertical target. A negative result from atan2 is a clockwise angle; adding 360° gives the equivalent anticlockwise angle.</p><p>The reference shot moves 3 units per tick with no gravity or drag. A hit means its path comes within 5 units of the target centre. Contact is checked along each movement segment, so a small target cannot be skipped between ticks. The trail continues beyond contact to show the direction.</p>`
},
{
 title:'Keep fractional movement in integers',
 intro:'The aim is already calculated. Fire it with two representations of velocity and see whether they reach the same target.',
 help:'Gold is the fractional reference. The dashed cyan path uses rounded integer velocity at the chosen scale.',
 prose:`<h2>Store a scaled value</h2><p>The opening angle is 32.8°. Its velocity is about (2.522, 1.625) units per tick. At scale 4, store round(vx × 4) = 10 and round(vy × 4) = 7. Decoding gives (10/4, 7/4) = (2.5, 1.75). Those values describe a slightly different direction and speed.</p><p>Fire without changing the angle. The fractional reference hits; the scale-4 path misses, passing 8.41 units from the target centre. Now choose scale 256 and repeat. Its smaller rounding error lets the fixed-point path hit. More precision is useful here, but costs a larger stored value.</p><h2>Position needs the same scale</h2><p>Begin stored position at zero. Each tick, add the stored velocity directly. After three ticks with stored X velocity 10, stored X position is 30. Divide by scale 4 only when interpreting or drawing it: 7.5 units. Rounding the position to a whole world unit after every tick would discard the fraction we meant to keep.</p><details class="question"><summary>At scale 256, what does stored velocity −384 represent? Where does it move from zero after four ticks?</summary><p>−384 / 256 = −1.5 units per tick. After four ticks, stored position is −1536, representing −6 units. Negative values use the same scale.</p></details><h2>State the limits</h2><p>We round halves away from zero, including negative values. At scales 4, 16 and 256, velocity fits a signed 16-bit integer (−32,768 to 32,767); position fits a signed 32-bit integer. Scaling increases precision but reduces the range available in a fixed width. At scale 256, signed 16-bit position would reach only about ±128 world units, so it would not cover this range.</p><p>This browser model stores the bounded integers exactly using JavaScript numbers. It does not emulate overflow. The reference also uses finite floating-point precision; it is not exact real-number arithmetic. We quantise velocity only, with no angle table. Timing, lookup tables and native instruction costs are separate questions.</p>`
}
];
