import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(new URL('../../../../website/package.json',import.meta.url));const {chromium}=require('@playwright/test');const AxeBuilder=require('@axe-core/playwright').default;
const out=process.argv[2]||'/tmp/aiming-lessons';await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'});const page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(String(e)));
async function set(id,value){await page.locator('#'+id).fill(String(value));await page.locator('#'+id).press('Tab');}
async function open(step){await page.goto('http://127.0.0.1:1990/lessons.html?step='+step);await page.waitForFunction(()=>document.querySelector('#working').textContent.length>0);}
try{
 for(let n=1;n<=6;n++){
  await open(n);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('[aria-current=step]').textContent(),String(n));assert.equal(await page.locator('#precision').count(),n===6?1:0);assert.equal(await page.locator('#fire').count(),n>=5?1:0);assert.equal(await page.locator('#solution').count(),n===5?1:0);
  if(n===1){assert.equal(await page.locator('#angle').count(),0);await set('x',-120);assert.match(await page.locator('#point-readout').textContent(),/-120.0, 90.0/);await set('x',90);await set('y',40);assert.match(await page.locator('#point-readout').textContent(),/90.0, 40.0/);}
  if(n===2){assert.match(await page.locator('#working').textContent(),/150.000/);await set('x',240);await set('y',180);assert.match(await page.locator('#working').textContent(),/300.000/);await set('x',0);await set('y',0);assert.match(await page.locator('#working').textContent(),/undefined/);}
  if(n===3){assert.match(await page.locator('#working').textContent(),/129.904/);await set('angle',90);assert.match(await page.locator('#working').textContent(),/vx = 0.000 · vy = 3.000/);await set('radius',225);assert.match(await page.locator('#point-readout').textContent(),/0.0, 225.0/);}
  if(n===4){await page.locator('[data-radians=quarter]').click();assert.match(await page.locator('#working').textContent(),/90.000°/);assert.match(await page.locator('#point-readout').textContent(),/0.0, 150.0/);await set('radius',100);await set('radians',1);assert.match(await page.locator('#working').textContent(),/57.296°/);assert.match(await page.locator('#working').textContent(),/= 100.000 units/);await page.locator('[data-radians=full]').click();assert.match(await page.locator('#point-readout').textContent(),/100.0, 0.0/);}
  if(n===5){await page.locator('#fire').click();assert.match(await page.locator('#result').textContent(),/miss/);for(let i=0;i<6;i++){await page.locator('#solution').evaluate(el=>el.open=true);await page.locator('#use-angle').click();await page.locator('#fire').click();assert.match(await page.locator('#result').textContent(),/Reference: hit/);await page.locator('#next-target').click();}}
  if(n===6){await page.locator('#fire').click();assert.match(await page.locator('#result').textContent(),/Reference: hit.*Fixed point: miss \(8.41/);await page.locator('#precision').selectOption('256');await page.locator('#fire').click();assert.match(await page.locator('#result').textContent(),/Reference: hit.*Fixed point: hit/);}
  await page.locator('#reset').click();const violations=(await new AxeBuilder({page}).analyze()).violations;assert.equal(violations.length,0,JSON.stringify(violations.map(v=>v.id)));
  for(const width of [390,1280]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${out}/step-${n}-${width}.png`,fullPage:true});}
  checks.push(`Step ${n}: focused controls, worked examples, reset, axe and narrow/desktop layout pass`);
 }
 await open(6);await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#fire').click();await page.waitForFunction(()=>document.querySelector('#result').textContent.startsWith('Reference:'));assert.match(await page.locator('#result').textContent(),/Fixed point: miss/);
 await page.locator('#fire').click();await set('angle',90);assert(await page.locator('#fire').isEnabled());assert(!((await page.locator('#result').textContent()).includes('Fixed point: miss')));
 assert.deepEqual(errors,[]);await fs.writeFile(out+'/results.json',JSON.stringify({checks,animation:'Normal playback completes; changed inputs cancel old results',errors},null,2)+'\n');
}finally{await browser.close();}
