40 PRINT "PRESS Y TO OPEN THE DOOR OR N TO RUN AWAY"
50 GET K$: IF K$="" THEN 50
60 IF K$="Y" THEN PRINT "THE DOOR CREAKS OPEN..."
70 IF K$="N" THEN PRINT "YOU DASH BACK INTO THE HALL."
80 IF K$<>"Y" AND K$<>"N" THEN PRINT "CONFUSED, YOU STAY PUT." : GOTO 50
