"""Original 24x16 artwork; prepare eight pixel offsets on the host, not in play."""
from pathlib import Path
ROOT=Path(__file__).resolve().parent
SHIP=[0x000000,0x001800,0x001800,0x003C00,0x003C00,0x007E00,0x00FF00,0x01DB80,0x03FFC0,0x07FFE0,0x0FFFF0,0x0CFF30,0x00FF00,0x006600,0x004200,0x000000]
METEOR=[0x007E00,0x03FF80,0x0FDFC0,0x1F87E0,0x3F03F0,0x7F83F8,0x7FE7FC,0xFFFDFC,0xF9FFFC,0xF0FFF8,0xF1F7F8,0x7FF3F0,0x3FFFE0,0x1FFFC0,0x07FF00,0x00F800]
METEOR=[METEOR[i] for i in [0,1,2,4,5,7,8,10,11,13,14,15]]+[0]*4
# A reproducible scattered field: each event is (x, speed, next delay).
import random
rng=random.Random(1986)
EVENTS=[(rng.randrange(8,225,2),rng.choice([2,3,4,5]),rng.randrange(6,11),rng.choice([-1,0,1]),2 if i%6==3 else 1) for i in range(120)]
STAR=[0x001800,0x001800,0x003C00,0x00FF00,0x03FFC0,0x00FF00,0x007E00,0x00E700,0x018180,0x0300C0,0,0,0,0,0,0]
def generate():
 lines=['; Generated by assets.py: original sprites, eight shifts, sixteen rows, four bytes per row.']
 for name,rows in [('ship',SHIP),('meteor',METEOR),('star',STAR)]:
  lines.append(name+'_sprites:')
  for shift in range(8):
   lines.append('; pixel offset '+str(shift))
   for row in rows:
    value=(row<<8)>>shift
    lines.append(' defb '+','.join('$%02X'%((value>>b)&255) for b in [24,16,8,0]))
 lines+=['meteor_events:']
 for event in EVENTS: lines.append(' defb '+','.join(map(str,(v&255 for v in event))))
 (ROOT/'assets.inc').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':generate()
