10 REM *** SCROLL RUNNER ***
20 PRINT CHR$(147);"SCROLL RUNNER"
30 VHEIGHT=10:VWIDTH=24:MAPW=64:LAST=MAPW-VWIDTH
40 DIM ROW$(VHEIGHT-1)
50 FOR R=0 TO VHEIGHT-1:READ ROW$(R):NEXT
60 PX=4:PY=5:OFFSET=0:SCROLL=0:WINCOUNT=0
70 ENX=32:ENY=5:ENDIR=1
80 SCORE=0:LIVES=3:STEP=5:NEXTT=STEP
90 TI$="000000"
100 PRINT "SURVIVE TO THE FAR GLOW. W/S MOVE. Q QUITS."
110 GOSUB 400
120 GET K$
130 IF K$="W" AND PY>1 THEN PY=PY-1
140 IF K$="S" AND PY<VHEIGHT-2 THEN PY=PY+1
150 IF K$="Q" THEN END
160 T=TI
170 IF T<NEXTT THEN GOTO 120
180 SCROLL=SCROLL+1:IF SCROLL=2 THEN SCROLL=0:IF OFFSET<LAST THEN OFFSET=OFFSET+1
190 IF OFFSET<LAST THEN WINCOUNT=0 ELSE WINCOUNT=WINCOUNT+1
200 ENY=ENY+ENDIR:IF ENY=1 OR ENY=VHEIGHT-2 THEN ENDIR=-ENDIR:ENY=ENY+ENDIR
210 GOSUB 400
220 WORLDX=OFFSET+PX
230 TILE$=MID$(ROW$(PY),WORLDX+1,1)
240 IF TILE$="#" OR TILE$="~" THEN LIVES=LIVES-1:OFFSET=OFFSET-2:IF OFFSET<0 THEN OFFSET=0
250 IF TILE$="#" OR TILE$="~" THEN PY=5:WINCOUNT=0:IF LIVES=0 THEN GOTO 540
260 IF TILE$="*" THEN SCORE=SCORE+50:ROW$(PY)=LEFT$(ROW$(PY),WORLDX)+"."+RIGHT$(ROW$(PY),MAPW-WORLDX-1)
270 IF WORLDX=ENX AND PY=ENY THEN LIVES=LIVES-1:OFFSET=OFFSET-2:IF OFFSET<0 THEN OFFSET=0:PY=5:WINCOUNT=0:IF LIVES=0 THEN GOTO 540
280 IF WINCOUNT>30 THEN GOTO 500
290 NEXTT=NEXTT+STEP
300 IF NEXTT<T THEN NEXTT=T+STEP
310 GOTO 120
400 PRINT CHR$(147);"SCROLL RUNNER  SCORE:";SCORE;"  LIVES:";LIVES
410 PRINT "REACH THE FAR GLOW WITHOUT CRASHING!"
420 FOR R=0 TO VHEIGHT-1
430 LINE$=MID$(ROW$(R),OFFSET+1,VWIDTH)
440 ENPOS=ENX-OFFSET+1
450 IF R=ENY AND ENPOS>=1 AND ENPOS<=VWIDTH THEN IF ENPOS=1 THEN LINE$="E"+MID$(LINE$,2,VWIDTH-1)
460 IF R=ENY AND ENPOS>1 AND ENPOS<VWIDTH THEN LINE$=LEFT$(LINE$,ENPOS-1)+"E"+MID$(LINE$,ENPOS+1,VWIDTH-ENPOS)
470 IF R=ENY AND ENPOS=VWIDTH THEN LINE$=LEFT$(LINE$,VWIDTH-1)+"E"
480 PPOS=PX+1
490 IF R=PY THEN IF PPOS=1 THEN LINE$="@"+MID$(LINE$,2,VWIDTH-1)
500 IF R=PY AND PPOS>1 AND PPOS<VWIDTH THEN LINE$=LEFT$(LINE$,PPOS-1)+"@"+MID$(LINE$,PPOS+1,VWIDTH-PPOS)
510 IF R=PY AND PPOS=VWIDTH THEN LINE$=LEFT$(LINE$,VWIDTH-1)+"@"
520 PRINT LINE$
530 NEXT R
538 RETURN
500 PRINT CHR$(147);"YOU CROSSED THE STATION!";:PRINT
510 PRINT "FINAL SCORE:";SCORE
520 END
540 PRINT CHR$(147);"OUT OF LIVES!";:PRINT
550 PRINT "FINAL SCORE:";SCORE
560 END
600 DATA "################################################################"
610 DATA "#....*....###....*....###....*.....###....*....###....*........#"
620 DATA "#....###....*..###....*.....~~~.....*....###....*..###....*....#"
630 DATA "#..###....*....###....*....###....*....###....*....###....*....#"
640 DATA "#..*....###....*....###....~~~....*....###....*....###....*....#"
650 DATA "#....*....~~~....*....###....*....###....*..~~~....*....###....#"
660 DATA "#....###....*....###....*....###....*....###....*....###....*..#"
670 DATA "#....*....###....*..~~~....*....###....*....###....*....~~~....#"
680 DATA "#....###....*....###....*....###....*....~~~....*....###....*..#"
690 DATA "################################################################"
